---
- name: handle credentials block
  block:
    - name: validate item.name is defined
      fail:
        msg: "missing required value for credential: item.name"
      when: item.name is undefined

    - name: validate item.kind is defined
      fail:
        msg: "missing required value for crendential: item.kind"
      when: item.kind is undefined

    - name: configure credential
      tower_credential:
        name: "{{ item.name }}"
        kind: "{{ item.kind }}"
        organization: "{{ item.organization | default(ansible_tower_default_organization) }}"

        description: "{{ item.description | default(omit) }}"
        vault_password: "{{ item.vault_password | default(omit) }}"
        state: "{{ item.state | default(omit) }}"

        tower_host: "{{ tower_host }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        tower_verify_ssl: "{{ tower_verify_ssl | default(omit) }}"

  connection: local
  tags:
    - credentials
